name: '微信定时推送任务'
on:
  schedule:
    - cron: '0 23 * * *'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.1
    - name: install pip packages
      run: |
        python -m pip install --upgrade pip
        pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
        pip install -r requirements.txt
    - name: '发送消息'
      run: |
        python ./main.py
